---
apiVersion: v1
kind: Service
metadata:
  name: gw-web-api-svc
spec:
  externalName: gw-web-api-svc.frontend.svc.cluster.local
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  sessionAffinity: None
  type: ExternalName
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: xrest-api-gw
  annotations:
    ingress.kubernetes.io/ssl-redirect: 'false'
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
  - host: api.xrest.pl
    http:
      paths:
      - path: /()(.*)
        pathType: Prefix
        backend:
          service:
            name: gw-web-api-svc
            port:
              number: 8080
