---
apiVersion: v1
kind: Service
metadata:
  name: mgm-dash-svc
spec:
  externalName: mgm-dash-svc.frontend.svc.cluster.local
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  sessionAffinity: None
  type: ExternalName
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: xrest-management-mg
  annotations:
    ingress.kubernetes.io/ssl-redirect: 'false'
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
  - host: mgm.xrest.pl
    http:
      paths:
      - path: /()(.*)
        pathType: Prefix
        backend:
          service:
            name: mgm-dash-svc
            port:
              number: 8081
