---
apiVersion: v1
kind: Service
metadata:
  name: xrest-identity-api-dev
  namespace: backend
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30101
  selector:
    app: xrest-identity-api
---
apiVersion: v1
kind: Service
metadata:
  name: xrest-restaurants-api-dev
  namespace: backend
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30102
  selector:
    app: xrest-restaurants-api
---
apiVersion: v1
kind: Service
metadata:
  name: xrest-orders-api-dev
  namespace: backend
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30103
  selector:
    app: xrest-orders-api
---
apiVersion: v1
kind: Service
metadata:
  name: xrest-images-api-dev
  namespace: backend
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30104
  selector:
    app: xrest-images-api
  
  