---
apiVersion: v1
kind: Service
metadata:
  name: sql-dev-no
  namespace: common-services
spec:
  type: NodePort
  ports:
  - port: 1433
    targetPort: 1433
    nodePort: 30005
  selector:
    app: mssql-dev