---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: sql-local
  namespace: common-services
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sql-local-storage
  namespace: common-services
spec:
  storageClassName: sql-local 
  capacity:
    storage: 40Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/d/_kubernetes/.volumes/sql
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sql-local-storage-claim
  namespace: common-services
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 40Gi
  storageClassName: sql-local
